# Generated by Django 5.1.4 on 2025-05-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_categories_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
