# Generated by Django 5.1.4 on 2025-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_name_category_title_remove_tag_name_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.SlugField(max_length=100),
        ),
    ]
