# Generated by Django 5.1.4 on 2025-06-15 17:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='posts/%Y/%m'),
        ),
    ]
