# Generated by Django 5.1.4 on 2025-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
