# Generated by Django 5.1.4 on 2025-06-16 08:33

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[posts.models.validate_persian_slug]),
        ),
    ]
