# Generated by Django 5.1.4 on 2025-06-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_media_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='slug',
        ),
    ]
