# Generated by Django 5.1.4 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Published', 'منتشر شده'), ('Pending', 'منتظر انتشار')], default='Published', max_length=50),
        ),
    ]
