# Generated by Django 5.1.4 on 2025-07-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_comment_options_rename_reply_to_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='votecomment',
            options={'verbose_name': 'رای کامنت', 'verbose_name_plural': 'رای کامنت ها'},
        ),
    ]
