# Generated by Django 5.1.4 on 2025-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Published', 'منتشر شده'), ('Pending', 'منتظر انتشار')], default='Pending', max_length=10),
        ),
    ]
