# Generated by Django 5.1.4 on 2025-07-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_postview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'بازدید پست', 'verbose_name_plural': ' بازدید پست ها'},
        ),
    ]
