# Generated by Django 5.1.4 on 2025-06-15 16:35

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_passwordresetcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/default_avatar.jpg', null=True, upload_to='avatars/%Y/%m'),
        ),
    ]
