# Generated by Django 5.1.4 on 2025-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeactions', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
